/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import de.abasgmh.infosystem.pdmDocuments.TestKeytech;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        TestKeytech classUnderTest = new TestKeytech();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.toString());
    }
}
